controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
  - name: gripper_controller
    type: GripperCommand
    action_ns: gripper_action
    default: true
    joints:
      - joint_6
      - joint_7
